name:                intcode
version:             0.3.0
github:              "TotallyNotChase/intcode"
license:             MIT
author:              "Chase"
maintainer:          "totallynotchase42@gmail.com"
copyright:           "TotallyNotChase"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/TotallyNotChase/intcode#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Wmissing-export-lists
- -Wpartial-fields
- -Wmissing-deriving-strategies

library:
  source-dirs: src
  exposed-modules:
  -  IntCode
  -  IntCode.ST
  ghc-options:
  - -O3

tests:
  intcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intcode
